// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NicholasHalmagyiFilip.DataModelCore;

namespace NicholasHalmagyiFilip.DataModelCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryDepotId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.HasIndex("CountryDepotId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.Depot", b =>
                {
                    b.Property<int>("DepotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepotName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepotId");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.DrugType", b =>
                {
                    b.Property<int>("DrugTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DrugTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("DrugTypeId");

                    b.ToTable("DrugTypes");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.DrugUnit", b =>
                {
                    b.Property<int>("DrugUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DrugUnitDepotId")
                        .HasColumnType("int");

                    b.Property<int>("DrugUnitDrugTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DrugUnitPickNumber")
                        .HasColumnType("int");

                    b.HasKey("DrugUnitId");

                    b.HasIndex("DrugUnitDepotId");

                    b.HasIndex("DrugUnitDrugTypeId");

                    b.ToTable("DrugUnits");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteId");

                    b.HasIndex("CountryCode");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.Country", b =>
                {
                    b.HasOne("NicholasHalmagyiFilip.DataModelCore.Models.Depot", "CountryDepot")
                        .WithMany("DepotCountries")
                        .HasForeignKey("CountryDepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryDepot");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.DrugUnit", b =>
                {
                    b.HasOne("NicholasHalmagyiFilip.DataModelCore.Models.Depot", "DrugUnitDepot")
                        .WithMany("DepotDrugUnits")
                        .HasForeignKey("DrugUnitDepotId");

                    b.HasOne("NicholasHalmagyiFilip.DataModelCore.Models.DrugType", "DrugUnitDrugType")
                        .WithMany()
                        .HasForeignKey("DrugUnitDrugTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrugUnitDepot");

                    b.Navigation("DrugUnitDrugType");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.Site", b =>
                {
                    b.HasOne("NicholasHalmagyiFilip.DataModelCore.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NicholasHalmagyiFilip.DataModelCore.Models.Depot", b =>
                {
                    b.Navigation("DepotCountries");

                    b.Navigation("DepotDrugUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
